
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: vuespringdb # Database name
      POSTGRES_USER: postgres # Database user
      POSTGRES_PASSWORD: 123456 # Database password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:latest
    ports:
      - 8080:8080

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile.yml
    container_name: pos-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081" # our port spring boot app runs on 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vuespringdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
