name: cafe_mobile
description: "Cafe App - Mobile Customer Ordering"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.0
  go_router: ^14.0.0
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.0
  qr_flutter: ^4.1.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
